<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevToys.Api" Version="2.0.8-preview" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="JsonToTypescriptExtension.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>JsonToTypescriptExtension.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="JsonToTypescriptExtension.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>JsonToTypescriptExtension.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
