//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.JsonToTypescript {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonToTypescriptExtension {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonToTypescriptExtension() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.JsonToTypescript.JsonToTypescriptExtension", typeof(JsonToTypescriptExtension).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Convert Json to Typescript code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertJsonToTypescriptConfigurationTitle {
            get {
                return ResourceManager.GetString("ConvertJsonToTypescriptConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input (JSON) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertJsonToTypescriptInputTitle {
            get {
                return ResourceManager.GetString("ConvertJsonToTypescriptInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output (Typescript) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertJsonToTypescriptOutputTitle {
            get {
                return ResourceManager.GetString("ConvertJsonToTypescriptOutputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert Json to Typescript code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello World! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelloWorldLabel {
            get {
                return ResourceManager.GetString("HelloWorldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON &gt; Typescript に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON &gt; TS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
    }
}
